version: "3"
services:
  spark_job:
    build: .
  spark-history-server:
    image: apache/spark
    command: /opt/spark/bin/spark-class -Dspark.history.fs.logDirectory=/var/log/spark/apps org.apache.spark.deploy.history.HistoryServer